export interface Language {
  code: string;
  name: string;
  nativeName: string;
  flag: string;
}

export const SUPPORTED_LANGUAGES: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇺🇸' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇵🇹' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano', flag: '🇮🇹' },
];

export const DEFAULT_LANGUAGE = 'en';

export const LOCALE_MAP: { [key: string]: string } = {
  en: 'en-US',
  es: 'es-ES',
  fr: 'fr-FR',
  de: 'de-DE',
  pt: 'pt-BR',
  it: 'it-IT',
};

export const SPEECH_RECOGNITION_LANG_MAP: { [key: string]: string } = {
  en: 'en-US',
  es: 'es-ES',
  fr: 'fr-FR',
  de: 'de-DE',
  pt: 'pt-BR',
  it: 'it-IT',
};

export interface Translations {
  [key: string]: string | string[] | Translations;
}

export const TRANSLATIONS: Record<string, Translations> = {
  en: {
    mainApp: {
      speechNotSupported: 'Speech recognition not supported in this browser.',
      permissionRequired: 'Permission required',
      microphonePermissionRequired: 'Microphone permission is required.',
      invalidUrl: 'Invalid URL',
      invalidUrlMessage: 'Webhook URL must start with http:// or https://',
      duplicate: 'Duplicate',
      duplicateUrlMessage: 'This URL is already added.',
      noData: 'No Data',
      noDataMessage: 'There is no stored data to send.',
      noActiveUrls: 'No Active URLs',
      noActiveUrlsMessage: 'Please activate at least one webhook URL in settings.',
      bulkSendError: 'Bulk Send Error',
      bulkSendErrorMessage: 'An unexpected error occurred during the bulk send process.',
      activeWebhooks: 'ACTIVE WEBHOOKS',
      dataQueue: 'DATA QUEUE',
      voiceMuted: 'Voice muted',
      voiceUnmuted: 'Voice unmuted',
      couldNotSendData: 'Could not send data',
      couldNotSaveSettings: 'Could not save settings',
      answerCopiedToClipboard: 'Answer copied to clipboard',
      bulkSendComplete: 'Bulk Send Complete',
      // Empty States and Instructions
      pressSpaceToRecord: 'Press SPACE to start recording',
      pressSendToConfirm: 'Press SEND to confirm calculation',
      useWebhookForSheets: 'Use WEBHOOK to send results to Google Sheets',
      pressRecordIcon: 'Press RECORD icon to start recording',
      useWebhookToSend: 'Use WEBHOOK to send results',
      resetCtrlBackspace: 'Reset (Ctrl+Backspace)',
      none: 'None',
      // Math and Speech Error Messages
      noEquationDetected: 'No Equation Detected',
      mathErrors: {
        sorryTryAgain: 'Sorry, please try again',
        error: 'Error',
        calculationFailed: 'Calculation failed',
        invalidExpression: 'Invalid expression',
      },
      speechErrors: {
        recognitionFailed: 'Speech recognition failed',
        microphoneError: 'Microphone error',
        noSpeechDetected: 'No speech detected',
        networkError: 'Network error during recognition',
      },
    },
    auth: {
      error: 'Error',
      authError: 'Authentication Error',
      signInSubtitle: 'Sign in to experience the future of calculation',
      continueWithGoogle: 'Continue with Google',
      fillAllFields: 'Please fill in all fields',
      validEmailRequired: 'Please enter a valid email address',
      passwordsDoNotMatch: 'Passwords do not match',
      passwordMinLength: 'Password must be at least 6 characters long',
      signInToContinue: 'Sign in to continue',
      settingUpAccount: 'Welcome to Calc AI',
      signOut: 'Sign Out',
      anonymousCat: 'Anonymous Cat',
      guestUser: 'Guest User',
      failedToSignOut: 'Failed to sign out',
      // Additional Auth Keys
      calculatorApp: 'Calculator App',
      createNewAccount: 'Create a new account',
      signUpPending: 'Sign Up Pending',
      checkEmailVerification:
        'Please check your email and click the verification link to complete registration.',
      signUp: 'Sign Up',
      alreadyHaveAccount: 'Already have an account? Sign In',
    },
    common: {
      error: 'Error',
      privacyPolicy: 'Privacy Policy',
      termsOfService: 'Terms of Service',
      screenNotExist: "This screen doesn't exist.",
      lastUpdated: 'Last Updated: May 9, 2025',
      duplicate: 'Duplicate',
      urlAlreadyAdded: 'This URL is already added.',
      pro: 'PRO',
      goToHomeScreen: 'Go to home screen!',
      comingSoon: '(soon)',
      // Additional Common UI Elements
      modal: 'Modal',
    },
    premium: {
      unlockPremiumFeatures: 'Unlock Premium Features',
      premium: 'PREMIUM',
      upgradeDescription:
        'Upgrade to Lifetime Premium Access to unlock webhook functionality and more premium features.',
      firstUsersLifetime: 'First 100 Users Get Lifetime Access',
      toPremium: 'to Premium! - Sign up here',
      unlimitedCalculations: 'Unlimited Calculations',
      webhookIntegration: 'Webhook Integration',
      historySync: 'History & Sync',
      features: {
        sendWebhooks: 'Send webhooks to any endpoint',
        unlimitedHistory: 'Unlimited calculation history',
        lifetimeAccess: 'One-time payment, lifetime access',
      },
      oneTimePayment: 'one-time payment',
      getLifetimeAccess: 'Get Lifetime Premium Access',
      modal: {
        unlockCalcAIPremium: 'Unlock CalcAI Premium',
        yearly: 'Yearly',
        lifetime: 'Lifetime',
        onceAYear: 'Once a year',
        oneTimePayment: 'One-time payment',
        continueWithGoogle: 'Continue with Google',
        getYearlyAccess: 'Get Yearly Access',
        getLifetimeAccess: 'Get Lifetime Access',
        getAccess: 'Get Access',
        restorePurchase: 'RESTORE PURCHASE',
        benefits: {
          unlimitedVoice: 'Unlimited voice calculations',
          webhookIntegrations: 'Webhook integrations (Google Sheets, Notion, etc.)',
          earlyAccess: 'Early access to new features',
          adFree: 'Ad-free experience',
          exportHistory: 'Export calculation history',
          advancedVoice: 'Advanced voice commands',
          prioritySupport: 'Priority support',
        },
      },
    },
    history: {
      calculationHistory: 'Calculation History',
      clearAll: 'Clear All',
      loadingHistory: 'Loading history...',
      noHistoryYet: 'No calculation history yet',
      historySubtext: 'Your calculations will appear here',
      clearAllConfirmTitle: 'Clear All Calculations',
      clearAllConfirmMessage:
        'Are you sure you want to delete all calculations? This cannot be undone.',
      cancel: 'Cancel',
      unknownDate: 'Unknown date',
      dayNames: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
      monthNames: [
        'January',
        'February',
        'March',
        'April',
        'May',
        'June',
        'July',
        'August',
        'September',
        'October',
        'November',
        'December',
      ],
    },
    editScreenInfo: {
      openCodeForScreen: 'Open up the code for this screen:',
      changeTextToUpdate:
        'Change any of the text, save the file, and your app will automatically update.',
      tapHereIfNotUpdating:
        "Tap here if your app doesn't automatically update after making changes",
    },
    forms: {
      // Form Labels and Placeholders
      email: 'Email',
      password: 'Password',
      passwordMinChars: 'Password (min. 6 characters)',
      confirmPassword: 'Confirm Password',
    },
    settings: {
      title: 'Settings',
      general: {
        title: 'General',
        inputBehavior: 'Input Behavior',
        muteVoiceOutput: 'Mute Voice Output (M)',
        newLineOnSend: 'New Line on Send',
        enableVibration: 'Enable Vibration',
        openInCalcMode: 'Open in Calculator Mode',
        webhooksSection: 'Webhooks',
        sendAnswerWithoutEquation: 'Send answer only',
        queueResultsForManualSending: 'Send automatically',
      },
      language: {
        title: 'Language',
        selectLanguage: 'Select Language',
      },
      webhooks: {
        title: 'Webhooks',
        createNew: 'Create a new webhook',
        enterTitle: 'Enter webhook title (optional)',
        enterUrl: 'Enter webhook URL (http:// or https://)',
        add: 'Add',
        myWebhooks: 'My webhooks',
        noWebhooksYet: 'No webhooks added yet',
        webhookTitle: 'Webhook Title (optional)',
        webhookUrl: 'Webhook URL',
        invalidUrl: 'Invalid URL',
        invalidUrlMessage: 'Webhook URL must be a valid URL starting with http:// or https://',
        duplicateUrl: 'Duplicate URL',
        duplicateUrlMessage: 'This webhook URL already exists.',
        success: 'Success',
        webhookUpdated: 'Webhook updated successfully!',
        saveError: 'Save Error',
        couldNotSave: 'Could not save the webhook URL.',
      },
      bulkData: {
        title: 'Bulk Data',
        items: 'items',
        deleteAll: 'Delete All',
        send: 'Send',
        sending: 'Sending...',
        item: 'Item',
        activateWebhook: 'Activate at least one webhook to enable sending',
        noActiveUrls: 'No Active URLs',
        activateMessage: 'Please activate at least one webhook URL.',
        sendComplete: 'Send Complete',
        successfullySentTo: 'Successfully sent to',
        endpoint: 'endpoint',
        endpoints: 'endpoints',
        failedToSendTo: 'Failed to send to',
        sendError: 'Send Error',
        errorSending: 'An error occurred while sending the data.',
        saveErrorMessage: 'An error occurred while saving the edited data.',
        deleteError: 'Delete Error',
        deleteErrorMessage: 'An error occurred while deleting the item.',
      },
    },
  },
  es: {
    mainApp: {
      speechNotSupported: 'Reconocimiento de voz no compatible con este navegador.',
      permissionRequired: 'Permiso requerido',
      microphonePermissionRequired: 'Se requiere permiso del micrófono.',
      invalidUrl: 'URL Inválida',
      invalidUrlMessage: 'La URL del webhook debe comenzar con http:// o https://',
      duplicate: 'Duplicado',
      duplicateUrlMessage: 'Esta URL ya está añadida.',
      noData: 'Sin Datos',
      noDataMessage: 'No hay datos almacenados para enviar.',
      noActiveUrls: 'No hay URLs Activas',
      noActiveUrlsMessage: 'Por favor active al menos una URL de webhook en configuración.',
      bulkSendError: 'Error de Envío Masivo',
      bulkSendErrorMessage: 'Ocurrió un error inesperado durante el proceso de envío masivo.',
      activeWebhooks: 'WEBHOOKS ACTIVOS',
      dataQueue: 'COLA DE DATOS',
      voiceMuted: 'Voz silenciada',
      voiceUnmuted: 'Voz no silenciada',
      couldNotSendData: 'No se pudieron enviar los datos',
      couldNotSaveSettings: 'No se pudo guardar la configuración',
      answerCopiedToClipboard: 'Respuesta copiada al portapapeles',
      bulkSendComplete: 'Envío Masivo Completado',
      // Empty States and Instructions
      pressSpaceToRecord: 'Presiona ESPACIO para comenzar a grabar',
      pressSendToConfirm: 'Presiona ENVIAR para confirmar el cálculo',
      useWebhookForSheets: 'Usa WEBHOOK para enviar resultados a Google Sheets',
      pressRecordIcon: 'Presiona el ícono de GRABAR para comenzar a grabar',
      useWebhookToSend: 'Usa WEBHOOK para enviar resultados',
      resetCtrlBackspace: 'Resetear (Ctrl+Retroceso)',
      none: 'Ninguno',
      // Math and Speech Error Messages
      noEquationDetected: 'No se Detectó Ecuación',
      mathErrors: {
        sorryTryAgain: 'Lo siento, inténtalo de nuevo',
        error: 'Error',
        calculationFailed: 'El cálculo falló',
        invalidExpression: 'Expresión inválida',
      },
      speechErrors: {
        recognitionFailed: 'Reconocimiento de voz falló',
        microphoneError: 'Error del micrófono',
        noSpeechDetected: 'No se detectó voz',
        networkError: 'Error de red durante el reconocimiento',
      },
    },
    auth: {
      error: 'Error',
      authError: 'Error de Autenticación',
      signInSubtitle: 'Inicie sesión para experimentar el futuro del cálculo',
      continueWithGoogle: 'Continuar con Google',
      fillAllFields: 'Por favor complete todos los campos',
      validEmailRequired: 'Por favor ingrese una dirección de correo válida',
      passwordsDoNotMatch: 'Las contraseñas no coinciden',
      passwordMinLength: 'La contraseña debe tener al menos 6 caracteres',
      signInToContinue: 'Inicie sesión para continuar',
      settingUpAccount: 'Bienvenido a Calc AI',
      signOut: 'Cerrar Sesión',
      anonymousCat: 'Gato Anónimo',
      guestUser: 'Usuario Invitado',
      failedToSignOut: 'Error al cerrar sesión',
      // Additional Auth Keys
      calculatorApp: 'Aplicación Calculadora',
      createNewAccount: 'Crear una nueva cuenta',
      signUpPending: 'Registro Pendiente',
      checkEmailVerification:
        'Por favor revise su correo electrónico y haga clic en el enlace de verificación para completar el registro.',
      signUp: 'Registrarse',
      alreadyHaveAccount: '¿Ya tienes una cuenta? Iniciar Sesión',
    },
    common: {
      error: 'Error',
      privacyPolicy: 'Política de Privacidad',
      termsOfService: 'Términos de Servicio',
      screenNotExist: 'Esta pantalla no existe.',
      lastUpdated: 'Última Actualización: 9 de Mayo, 2025',
      duplicate: 'Duplicado',
      urlAlreadyAdded: 'Esta URL ya fue añadida.',
      pro: 'PRO',
      goToHomeScreen: '¡Ir a la pantalla de inicio!',
      comingSoon: '(próximamente)',
      // Additional Common UI Elements
      modal: 'Modal',
    },
    premium: {
      unlockPremiumFeatures: 'Desbloquear Funciones Premium',
      premium: 'PREMIUM',
      upgradeDescription:
        'Actualice a Acceso Premium de Por Vida para desbloquear la funcionalidad de webhook y más funciones premium.',
      firstUsersLifetime: 'Los Primeros 100 Usuarios Obtienen Acceso de Por Vida',
      toPremium: '¡a Premium! - Regístrese aquí',
      unlimitedCalculations: 'Cálculos Ilimitados',
      webhookIntegration: 'Integración de Webhooks',
      historySync: 'Historial y Sincronización',
      features: {
        sendWebhooks: 'Enviar webhooks a cualquier endpoint',
        unlimitedHistory: 'Historial de cálculos ilimitado',
        lifetimeAccess: 'Pago único, acceso de por vida',
      },
      oneTimePayment: 'pago único',
      getLifetimeAccess: 'Obtener Acceso Premium de Por Vida',
      modal: {
        unlockCalcAIPremium: 'Desbloquear CalcAI Premium',
        yearly: 'Anual',
        lifetime: 'De Por Vida',
        onceAYear: 'Una vez al año',
        oneTimePayment: 'Pago único',
        continueWithGoogle: 'Continuar con Google',
        getYearlyAccess: 'Obtener Acceso Anual',
        getLifetimeAccess: 'Obtener Acceso de Por Vida',
        getAccess: 'Obtener Acceso',
        restorePurchase: 'RESTAURAR COMPRA',
        benefits: {
          unlimitedVoice: 'Cálculos de voz ilimitados',
          webhookIntegrations: 'Integraciones de webhook (Google Sheets, Notion, etc.)',
          earlyAccess: 'Acceso anticipado a nuevas funciones',
          adFree: 'Experiencia sin anuncios',
          exportHistory: 'Exportar historial de cálculos',
          advancedVoice: 'Comandos de voz avanzados',
          prioritySupport: 'Soporte prioritario',
        },
      },
    },
    history: {
      calculationHistory: 'Historial de Cálculos',
      clearAll: 'Limpiar Todo',
      loadingHistory: 'Cargando historial...',
      noHistoryYet: 'No hay historial de cálculos aún',
      historySubtext: 'Sus cálculos aparecerán aquí',
      clearAllConfirmTitle: 'Limpiar Todos los Cálculos',
      clearAllConfirmMessage:
        '¿Está seguro de que desea eliminar todos los cálculos? Esto no se puede deshacer.',
      cancel: 'Cancelar',
      unknownDate: 'Fecha desconocida',
      dayNames: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
      monthNames: [
        'Enero',
        'Febrero',
        'Marzo',
        'Abril',
        'Mayo',
        'Junio',
        'Julio',
        'Agosto',
        'Septiembre',
        'Octubre',
        'Noviembre',
        'Diciembre',
      ],
    },
    editScreenInfo: {
      openCodeForScreen: 'Abra el código de esta pantalla:',
      changeTextToUpdate:
        'Cambie cualquier texto, guarde el archivo y su aplicación se actualizará automáticamente.',
      tapHereIfNotUpdating:
        'Toque aquí si su aplicación no se actualiza automáticamente después de realizar cambios',
    },
    forms: {
      // Form Labels and Placeholders
      email: 'Correo Electrónico',
      password: 'Contraseña',
      passwordMinChars: 'Contraseña (mín. 6 caracteres)',
      confirmPassword: 'Confirmar Contraseña',
    },
    settings: {
      title: 'Configuración',
      general: {
        title: 'General',
        inputBehavior: 'Comportamiento de Entrada',
        muteVoiceOutput: 'Silenciar Salida de Voz (M)',
        newLineOnSend: 'Nueva Línea al Enviar',
        enableVibration: 'Habilitar Vibración',
        openInCalcMode: 'Abrir en Modo Calculadora',
        webhooksSection: 'Webhooks',
        sendAnswerWithoutEquation: 'Enviar solamente la respuesta',
        queueResultsForManualSending: 'Enviar automáticamente',
      },
      language: {
        title: 'Idioma',
        selectLanguage: 'Seleccionar Idioma',
      },
      webhooks: {
        title: 'Webhooks',
        createNew: 'Crear un nuevo webhook',
        enterTitle: 'Ingrese título del webhook (opcional)',
        enterUrl: 'Ingrese URL del webhook (http:// o https://)',
        add: 'Añadir',
        myWebhooks: 'Mis webhooks',
        noWebhooksYet: 'No se han añadido webhooks aún',
        webhookTitle: 'Título del Webhook (opcional)',
        webhookUrl: 'URL del Webhook',
        invalidUrl: 'URL Inválida',
        invalidUrlMessage: 'La URL del webhook debe ser válida y comenzar con http:// o https://',
        duplicateUrl: 'URL Duplicada',
        duplicateUrlMessage: 'Esta URL del webhook ya existe.',
        success: 'Éxito',
        webhookUpdated: '¡Webhook actualizado exitosamente!',
        saveError: 'Error al Guardar',
        couldNotSave: 'No se pudo guardar la URL del webhook.',
      },
      bulkData: {
        title: 'Datos Masivos',
        items: 'elementos',
        deleteAll: 'Eliminar Todo',
        send: 'Enviar',
        sending: 'Enviando...',
        item: 'Elemento',
        activateWebhook: 'Active al menos un webhook para habilitar el envío',
        noActiveUrls: 'No hay URLs Activas',
        activateMessage: 'Por favor active al menos una URL de webhook.',
        sendComplete: 'Envío Completo',
        successfullySentTo: 'Enviado exitosamente a',
        endpoint: 'endpoint',
        endpoints: 'endpoints',
        failedToSendTo: 'Error al enviar a',
        sendError: 'Error de Envío',
        errorSending: 'Ocurrió un error al enviar los datos.',
        saveErrorMessage: 'Ocurrió un error al guardar los datos editados.',
        deleteError: 'Error de Eliminación',
        deleteErrorMessage: 'Ocurrió un error al eliminar el elemento.',
      },
    },
  },
  fr: {
    mainApp: {
      speechNotSupported: 'Reconnaissance vocale non prise en charge par ce navigateur.',
      permissionRequired: 'Permission requise',
      microphonePermissionRequired: "L'autorisation du microphone est requise.",
      invalidUrl: 'URL Invalide',
      invalidUrlMessage: "L'URL du webhook doit commencer par http:// ou https://",
      duplicate: 'Dupliquer',
      duplicateUrlMessage: 'Cette URL est déjà ajoutée.',
      noData: 'Aucune Donnée',
      noDataMessage: "Il n'y a aucune donnée stockée à envoyer.",
      noActiveUrls: 'Aucune URL Active',
      noActiveUrlsMessage: 'Veuillez activer au moins une URL de webhook dans les paramètres.',
      bulkSendError: "Erreur d'Envoi en Lot",
      bulkSendErrorMessage:
        "Une erreur inattendue s'est produite pendant le processus d'envoi en lot.",
      activeWebhooks: 'WEBHOOKS ACTIFS',
      dataQueue: 'FILE DE DONNÉES',
      voiceMuted: 'Voix désactivée',
      voiceUnmuted: 'Voix activée',
      couldNotSendData: "Impossible d'envoyer les données",
      couldNotSaveSettings: 'Impossible de sauvegarder les paramètres',
      answerCopiedToClipboard: 'Réponse copiée dans le presse-papiers',
      bulkSendComplete: 'Envoi en Masse Terminé',
      // Empty States and Instructions
      pressSpaceToRecord: "Appuyez sur ESPACE pour commencer l'enregistrement",
      pressSendToConfirm: 'Appuyez sur ENVOYER pour confirmer le calcul',
      useWebhookForSheets: 'Utilisez WEBHOOK pour envoyer les résultats vers Google Sheets',
      pressRecordIcon: "Appuyez sur l'icône ENREGISTRER pour commencer l'enregistrement",
      useWebhookToSend: 'Utilisez WEBHOOK pour envoyer les résultats',
      resetCtrlBackspace: 'Réinitialiser (Ctrl+Retour arrière)',
      none: 'Aucun',
      // Math and Speech Error Messages
      noEquationDetected: 'Aucune Équation Détectée',
      mathErrors: {
        sorryTryAgain: 'Désolé, veuillez réessayer',
        error: 'Erreur',
        calculationFailed: 'Échec du calcul',
        invalidExpression: 'Expression invalide',
      },
      speechErrors: {
        recognitionFailed: 'Reconnaissance vocale échouée',
        microphoneError: 'Erreur de microphone',
        noSpeechDetected: 'Aucun discours détecté',
        networkError: 'Erreur réseau lors de la reconnaissance',
      },
    },
    auth: {
      error: 'Erreur',
      authError: "Erreur d'Authentification",
      signInSubtitle: "Connectez-vous pour découvrir l'avenir du calcul",
      continueWithGoogle: 'Continuer avec Google',
      fillAllFields: 'Veuillez remplir tous les champs',
      validEmailRequired: 'Veuillez saisir une adresse e-mail valide',
      passwordsDoNotMatch: 'Les mots de passe ne correspondent pas',
      passwordMinLength: 'Le mot de passe doit contenir au moins 6 caractères',
      signInToContinue: 'Connectez-vous pour continuer',
      settingUpAccount: 'Bienvenue sur Calc AI',
      signOut: 'Se Déconnecter',
      anonymousCat: 'Chat Anonyme',
      guestUser: 'Utilisateur Invité',
      failedToSignOut: 'Échec de la déconnexion',
      // Additional Auth Keys
      calculatorApp: 'Application Calculatrice',
      createNewAccount: 'Créer un nouveau compte',
      signUpPending: 'Inscription en Attente',
      checkEmailVerification:
        "Veuillez vérifier votre e-mail et cliquer sur le lien de vérification pour terminer l'inscription.",
      signUp: "S'inscrire",
      alreadyHaveAccount: 'Vous avez déjà un compte ? Se connecter',
    },
    common: {
      error: 'Erreur',
      privacyPolicy: 'Politique de Confidentialité',
      termsOfService: "Conditions d'Utilisation",
      screenNotExist: "Cet écran n'existe pas.",
      lastUpdated: 'Dernière Mise à Jour : 9 Mai 2025',
      duplicate: 'Dupliquer',
      urlAlreadyAdded: 'Cette URL a déjà été ajoutée.',
      pro: 'PRO',
      goToHomeScreen: "Aller à l'écran d'accueil !",
      comingSoon: '(bientôt)',
      // Additional Common UI Elements
      modal: 'Modal',
    },
    premium: {
      unlockPremiumFeatures: 'Débloquer les Fonctionnalités Premium',
      premium: 'PREMIUM',
      upgradeDescription:
        "Passez à l'Accès Premium à Vie pour débloquer la fonctionnalité webhook et plus de fonctionnalités premium.",
      firstUsersLifetime: 'Les 100 Premiers Utilisateurs Obtiennent un Accès à Vie',
      toPremium: 'à Premium ! - Inscrivez-vous ici',
      unlimitedCalculations: 'Calculs Illimités',
      webhookIntegration: 'Intégration de Webhooks',
      historySync: 'Historique et Synchronisation',
      features: {
        sendWebhooks: "Envoyer des webhooks vers n'importe quel endpoint",
        unlimitedHistory: 'Historique de calculs illimité',
        lifetimeAccess: 'Paiement unique, accès à vie',
      },
      oneTimePayment: 'paiement unique',
      getLifetimeAccess: "Obtenir l'Accès Premium à Vie",
      modal: {
        unlockCalcAIPremium: 'Débloquer CalcAI Premium',
        yearly: 'Annuel',
        lifetime: 'À Vie',
        onceAYear: 'Une fois par an',
        oneTimePayment: 'Paiement unique',
        continueWithGoogle: 'Continuer avec Google',
        getYearlyAccess: "Obtenir l'Accès Annuel",
        getLifetimeAccess: "Obtenir l'Accès à Vie",
        getAccess: "Obtenir l'Accès",
        restorePurchase: "RESTAURER L'ACHAT",
        benefits: {
          unlimitedVoice: 'Calculs vocaux illimités',
          webhookIntegrations: 'Intégrations webhook (Google Sheets, Notion, etc.)',
          earlyAccess: 'Accès anticipé aux nouvelles fonctionnalités',
          adFree: 'Expérience sans publicité',
          exportHistory: "Exporter l'historique des calculs",
          advancedVoice: 'Commandes vocales avancées',
          prioritySupport: 'Support prioritaire',
        },
      },
    },
    history: {
      calculationHistory: 'Historique des Calculs',
      clearAll: 'Effacer Tout',
      loadingHistory: "Chargement de l'historique...",
      noHistoryYet: 'Aucun historique de calculs pour le moment',
      historySubtext: 'Vos calculs apparaîtront ici',
      clearAllConfirmTitle: 'Effacer Tous les Calculs',
      clearAllConfirmMessage:
        'Êtes-vous sûr de vouloir supprimer tous les calculs ? Cette action ne peut pas être annulée.',
      cancel: 'Annuler',
      unknownDate: 'Date inconnue',
      dayNames: ['Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi'],
      monthNames: [
        'Janvier',
        'Février',
        'Mars',
        'Avril',
        'Mai',
        'Juin',
        'Juillet',
        'Août',
        'Septembre',
        'Octobre',
        'Novembre',
        'Décembre',
      ],
    },
    editScreenInfo: {
      openCodeForScreen: 'Ouvrez le code de cet écran :',
      changeTextToUpdate:
        "Changez n'importe quel texte, sauvegardez le fichier, et votre application se mettra à jour automatiquement.",
      tapHereIfNotUpdating:
        'Appuyez ici si votre application ne se met pas à jour automatiquement après avoir effectué des modifications',
    },
    forms: {
      // Form Labels and Placeholders
      email: 'E-mail',
      password: 'Mot de passe',
      passwordMinChars: 'Mot de passe (min. 6 caractères)',
      confirmPassword: 'Confirmer le mot de passe',
    },
    settings: {
      title: 'Paramètres',
      general: {
        title: 'Général',
        inputBehavior: 'Comportement de Saisie',
        muteVoiceOutput: 'Couper la Sortie Vocale (M)',
        newLineOnSend: "Nouvelle Ligne à l'Envoi",
        enableVibration: 'Activer la Vibration',
        openInCalcMode: 'Ouvrir en Mode Calculatrice',
        webhooksSection: 'Webhooks',
        sendAnswerWithoutEquation: 'Envoyer seulement la réponse',
        queueResultsForManualSending: 'Envoyer automatiquement',
      },
      language: {
        title: 'Langue',
        selectLanguage: 'Sélectionner la Langue',
      },
      webhooks: {
        title: 'Webhooks',
        createNew: 'Créer un nouveau webhook',
        enterTitle: 'Entrez le titre du webhook (optionnel)',
        enterUrl: "Entrez l'URL du webhook (http:// ou https://)",
        add: 'Ajouter',
        myWebhooks: 'Mes webhooks',
        noWebhooksYet: 'Aucun webhook ajouté pour le moment',
        webhookTitle: 'Titre du Webhook (optionnel)',
        webhookUrl: 'URL du Webhook',
        invalidUrl: 'URL Invalide',
        invalidUrlMessage: "L'URL du webhook doit être valide et commencer par http:// ou https://",
        duplicateUrl: 'URL Dupliquée',
        duplicateUrlMessage: 'Cette URL de webhook existe déjà.',
        success: 'Succès',
        webhookUpdated: 'Webhook mis à jour avec succès !',
        saveError: 'Erreur de Sauvegarde',
        couldNotSave: "Impossible de sauvegarder l'URL du webhook.",
      },
      bulkData: {
        title: 'Données en Lot',
        items: 'éléments',
        deleteAll: 'Tout Supprimer',
        send: 'Envoyer',
        sending: 'Envoi en cours...',
        item: 'Élément',
        activateWebhook: "Activez au moins un webhook pour permettre l'envoi",
        noActiveUrls: 'Aucune URL Active',
        activateMessage: 'Veuillez activer au moins une URL de webhook.',
        sendComplete: 'Envoi Terminé',
        successfullySentTo: 'Envoyé avec succès à',
        endpoint: 'endpoint',
        endpoints: 'endpoints',
        failedToSendTo: "Échec de l'envoi vers",
        sendError: "Erreur d'Envoi",
        errorSending: "Une erreur s'est produite lors de l'envoi des données.",
        saveErrorMessage: "Une erreur s'est produite lors de la sauvegarde des données modifiées.",
        deleteError: 'Erreur de Suppression',
        deleteErrorMessage: "Une erreur s'est produite lors de la suppression de l'élément.",
      },
    },
  },
  de: {
    mainApp: {
      speechNotSupported: 'Spracherkennung wird von diesem Browser nicht unterstützt.',
      permissionRequired: 'Berechtigung erforderlich',
      microphonePermissionRequired: 'Mikrofonberechtigung ist erforderlich.',
      invalidUrl: 'Ungültige URL',
      invalidUrlMessage: 'Webhook-URL muss mit http:// oder https:// beginnen',
      duplicate: 'Duplikat',
      duplicateUrlMessage: 'Diese URL ist bereits hinzugefügt.',
      noData: 'Keine Daten',
      noDataMessage: 'Es sind keine gespeicherten Daten zum Senden vorhanden.',
      noActiveUrls: 'Keine Aktiven URLs',
      noActiveUrlsMessage: 'Bitte aktivieren Sie mindestens eine Webhook-URL in den Einstellungen.',
      bulkSendError: 'Massen-Sendefehler',
      bulkSendErrorMessage:
        'Ein unerwarteter Fehler ist während des Massen-Sendeprozesses aufgetreten.',
      activeWebhooks: 'AKTIVE WEBHOOKS',
      dataQueue: 'DATENWARTESCHLANGE',
      voiceMuted: 'Stimme stummgeschaltet',
      voiceUnmuted: 'Stimme nicht stummgeschaltet',
      couldNotSendData: 'Daten konnten nicht gesendet werden',
      couldNotSaveSettings: 'Einstellungen konnten nicht gespeichert werden',
      answerCopiedToClipboard: 'Antwort in die Zwischenablage kopiert',
      bulkSendComplete: 'Massen-Sendung Abgeschlossen',
      // Empty States and Instructions
      pressSpaceToRecord: 'Drücken Sie LEERTASTE um die Aufnahme zu starten',
      pressSendToConfirm: 'Drücken Sie SENDEN um die Berechnung zu bestätigen',
      useWebhookForSheets: 'Verwenden Sie WEBHOOK um Ergebnisse an Google Sheets zu senden',
      pressRecordIcon: 'Drücken Sie das AUFNAHME-SYMBOL um die Aufnahme zu starten',
      useWebhookToSend: 'Verwenden Sie WEBHOOK um Ergebnisse zu senden',
      resetCtrlBackspace: 'Zurücksetzen (Strg+Rücktaste)',
      none: 'Keine',
      // Math and Speech Error Messages
      noEquationDetected: 'Keine Gleichung Erkannt',
      mathErrors: {
        sorryTryAgain: 'Entschuldigung, bitte versuchen Sie es erneut',
        error: 'Fehler',
        calculationFailed: 'Berechnung fehlgeschlagen',
        invalidExpression: 'Ungültiger Ausdruck',
      },
      speechErrors: {
        recognitionFailed: 'Spracherkennung fehlgeschlagen',
        microphoneError: 'Mikrofonfehler',
        noSpeechDetected: 'Keine Sprache erkannt',
        networkError: 'Netzwerkfehler während der Erkennung',
      },
    },
    auth: {
      error: 'Fehler',
      authError: 'Authentifizierungsfehler',
      signInSubtitle: 'Melden Sie sich an, um die Zukunft der Berechnung zu erleben',
      continueWithGoogle: 'Mit Google Fortfahren',
      fillAllFields: 'Bitte füllen Sie alle Felder aus',
      validEmailRequired: 'Bitte geben Sie eine gültige E-Mail-Adresse ein',
      passwordsDoNotMatch: 'Passwörter stimmen nicht überein',
      passwordMinLength: 'Passwort muss mindestens 6 Zeichen lang sein',
      signInToContinue: 'Anmelden um fortzufahren',
      settingUpAccount: 'Willkommen bei Calc AI',
      signOut: 'Abmelden',
      anonymousCat: 'Anonyme Katze',
      guestUser: 'Gastbenutzer',
      failedToSignOut: 'Abmeldung fehlgeschlagen',
      // Additional Auth Keys
      calculatorApp: 'Rechner-App',
      createNewAccount: 'Neues Konto erstellen',
      signUpPending: 'Registrierung Ausstehend',
      checkEmailVerification:
        'Bitte überprüfen Sie Ihre E-Mail und klicken Sie auf den Bestätigungslink, um die Registrierung abzuschließen.',
      signUp: 'Registrieren',
      alreadyHaveAccount: 'Haben Sie bereits ein Konto? Anmelden',
    },
    common: {
      error: 'Fehler',
      privacyPolicy: 'Datenschutzrichtlinie',
      termsOfService: 'Nutzungsbedingungen',
      screenNotExist: 'Dieser Bildschirm existiert nicht.',
      lastUpdated: 'Zuletzt Aktualisiert: 9. Mai 2025',
      duplicate: 'Duplikat',
      urlAlreadyAdded: 'Diese URL wurde bereits hinzugefügt.',
      pro: 'PRO',
      goToHomeScreen: 'Zum Startbildschirm gehen!',
      comingSoon: '(bald)',
      // Additional Common UI Elements
      modal: 'Modal',
    },
    premium: {
      unlockPremiumFeatures: 'Premium-Funktionen Freischalten',
      premium: 'PREMIUM',
      upgradeDescription:
        'Upgraden Sie auf lebenslangen Premium-Zugang, um Webhook-Funktionalität und weitere Premium-Funktionen freizuschalten.',
      firstUsersLifetime: 'Die Ersten 100 Benutzer Erhalten Lebenslangen Zugang',
      toPremium: 'zu Premium! - Hier anmelden',
      unlimitedCalculations: 'Unbegrenzte Berechnungen',
      webhookIntegration: 'Webhook-Integration',
      historySync: 'Verlauf & Synchronisation',
      features: {
        sendWebhooks: 'Webhooks an jeden Endpunkt senden',
        unlimitedHistory: 'Unbegrenzter Berechnungsverlauf',
        lifetimeAccess: 'Einmalige Zahlung, lebenslanger Zugang',
      },
      oneTimePayment: 'einmalige Zahlung',
      getLifetimeAccess: 'Lebenslangen Premium-Zugang Erhalten',
      modal: {
        unlockCalcAIPremium: 'CalcAI Premium Freischalten',
        yearly: 'Jährlich',
        lifetime: 'Lebenslang',
        onceAYear: 'Einmal pro Jahr',
        oneTimePayment: 'Einmalige Zahlung',
        continueWithGoogle: 'Mit Google Fortfahren',
        getYearlyAccess: 'Jährlichen Zugang Erhalten',
        getLifetimeAccess: 'Lebenslangen Zugang Erhalten',
        getAccess: 'Zugang Erhalten',
        restorePurchase: 'KAUF WIEDERHERSTELLEN',
        benefits: {
          unlimitedVoice: 'Unbegrenzte Sprachberechnungen',
          webhookIntegrations: 'Webhook-Integrationen (Google Sheets, Notion, etc.)',
          earlyAccess: 'Frühzeitiger Zugang zu neuen Funktionen',
          adFree: 'Werbefreies Erlebnis',
          exportHistory: 'Berechnungsverlauf exportieren',
          advancedVoice: 'Erweiterte Sprachbefehle',
          prioritySupport: 'Prioritäts-Support',
        },
      },
    },
    history: {
      calculationHistory: 'Berechnungsverlauf',
      clearAll: 'Alle Löschen',
      loadingHistory: 'Verlauf wird geladen...',
      noHistoryYet: 'Noch kein Berechnungsverlauf',
      historySubtext: 'Ihre Berechnungen werden hier erscheinen',
      clearAllConfirmTitle: 'Alle Berechnungen Löschen',
      clearAllConfirmMessage:
        'Sind Sie sicher, dass Sie alle Berechnungen löschen möchten? Dies kann nicht rückgängig gemacht werden.',
      cancel: 'Abbrechen',
      unknownDate: 'Unbekanntes Datum',
      dayNames: ['Sonntag', 'Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag'],
      monthNames: [
        'Januar',
        'Februar',
        'März',
        'April',
        'Mai',
        'Juni',
        'Juli',
        'August',
        'September',
        'Oktober',
        'November',
        'Dezember',
      ],
    },
    editScreenInfo: {
      openCodeForScreen: 'Öffnen Sie den Code für diesen Bildschirm:',
      changeTextToUpdate:
        'Ändern Sie einen beliebigen Text, speichern Sie die Datei, und Ihre App wird automatisch aktualisiert.',
      tapHereIfNotUpdating:
        'Tippen Sie hier, wenn sich Ihre App nach Änderungen nicht automatisch aktualisiert',
    },
    forms: {
      // Form Labels and Placeholders
      email: 'E-Mail',
      password: 'Passwort',
      passwordMinChars: 'Passwort (min. 6 Zeichen)',
      confirmPassword: 'Passwort Bestätigen',
    },
    settings: {
      title: 'Einstellungen',
      general: {
        title: 'Allgemein',
        inputBehavior: 'Eingabeverhalten',
        muteVoiceOutput: 'Sprachausgabe Stummschalten (M)',
        newLineOnSend: 'Neue Zeile beim Senden',
        enableVibration: 'Vibration Aktivieren',
        openInCalcMode: 'Im Rechnermodus Öffnen',
        webhooksSection: 'Webhooks',
        sendAnswerWithoutEquation: 'Nur Antwort senden',
        queueResultsForManualSending: 'Automatisch senden',
      },
      language: {
        title: 'Sprache',
        selectLanguage: 'Sprache Auswählen',
      },
      webhooks: {
        title: 'Webhooks',
        createNew: 'Neuen Webhook erstellen',
        enterTitle: 'Webhook-Titel eingeben (optional)',
        enterUrl: 'Webhook-URL eingeben (http:// oder https://)',
        add: 'Hinzufügen',
        myWebhooks: 'Meine Webhooks',
        noWebhooksYet: 'Noch keine Webhooks hinzugefügt',
        webhookTitle: 'Webhook-Titel (optional)',
        webhookUrl: 'Webhook-URL',
        invalidUrl: 'Ungültige URL',
        invalidUrlMessage: 'Webhook-URL muss gültig sein und mit http:// oder https:// beginnen',
        duplicateUrl: 'Doppelte URL',
        duplicateUrlMessage: 'Diese Webhook-URL existiert bereits.',
        success: 'Erfolg',
        webhookUpdated: 'Webhook erfolgreich aktualisiert!',
        saveError: 'Speicherfehler',
        couldNotSave: 'Webhook-URL konnte nicht gespeichert werden.',
      },
      bulkData: {
        title: 'Massendaten',
        items: 'Elemente',
        deleteAll: 'Alle Löschen',
        send: 'Senden',
        sending: 'Sende...',
        item: 'Element',
        activateWebhook: 'Aktivieren Sie mindestens einen Webhook um das Senden zu ermöglichen',
        noActiveUrls: 'Keine Aktiven URLs',
        activateMessage: 'Bitte aktivieren Sie mindestens eine Webhook-URL.',
        sendComplete: 'Senden Abgeschlossen',
        successfullySentTo: 'Erfolgreich gesendet an',
        endpoint: 'Endpunkt',
        endpoints: 'Endpunkte',
        failedToSendTo: 'Senden fehlgeschlagen an',
        sendError: 'Sendefehler',
        errorSending: 'Beim Senden der Daten ist ein Fehler aufgetreten.',
        saveErrorMessage: 'Beim Speichern der bearbeiteten Daten ist ein Fehler aufgetreten.',
        deleteError: 'Löschfehler',
        deleteErrorMessage: 'Beim Löschen des Elements ist ein Fehler aufgetreten.',
      },
    },
  },
  pt: {
    mainApp: {
      speechNotSupported: 'Reconhecimento de voz não suportado neste navegador.',
      permissionRequired: 'Permissão necessária',
      microphonePermissionRequired: 'Permissão do microfone é necessária.',
      invalidUrl: 'URL Inválida',
      invalidUrlMessage: 'URL do webhook deve começar com http:// ou https://',
      duplicate: 'Duplicado',
      duplicateUrlMessage: 'Esta URL já está adicionada.',
      noData: 'Sem Dados',
      noDataMessage: 'Não há dados armazenados para enviar.',
      noActiveUrls: 'Nenhuma URL Ativa',
      noActiveUrlsMessage: 'Por favor ative pelo menos uma URL de webhook nas configurações.',
      bulkSendError: 'Erro de Envio em Massa',
      bulkSendErrorMessage: 'Ocorreu um erro inesperado durante o processo de envio em massa.',
      activeWebhooks: 'WEBHOOKS ATIVOS',
      dataQueue: 'FILA DE DADOS',
      voiceMuted: 'Voz sem som',
      voiceUnmuted: 'Voz com som',
      couldNotSendData: 'Não foi possível enviar os dados',
      couldNotSaveSettings: 'Não foi possível salvar as configurações',
      answerCopiedToClipboard: 'Resposta copiada para a área de transferência',
      bulkSendComplete: 'Envio em Massa Concluído',
      // Empty States and Instructions
      pressSpaceToRecord: 'Pressione ESPAÇO para começar a gravar',
      pressSendToConfirm: 'Pressione ENVIAR para confirmar o cálculo',
      useWebhookForSheets: 'Use WEBHOOK para enviar resultados para o Google Sheets',
      pressRecordIcon: 'Pressione o ícone GRAVAR para começar a gravar',
      useWebhookToSend: 'Use WEBHOOK para enviar resultados',
      resetCtrlBackspace: 'Resetar (Ctrl+Backspace)',
      none: 'Nenhum',
      // Math and Speech Error Messages
      noEquationDetected: 'Nenhuma Equação Detectada',
      mathErrors: {
        sorryTryAgain: 'Desculpe, tente novamente',
        error: 'Erro',
        calculationFailed: 'Cálculo falhou',
        invalidExpression: 'Expressão inválida',
      },
      speechErrors: {
        recognitionFailed: 'Reconhecimento de voz falhou',
        microphoneError: 'Erro do microfone',
        noSpeechDetected: 'Nenhuma fala detectada',
        networkError: 'Erro de rede durante o reconhecimento',
      },
    },
    auth: {
      error: 'Erro',
      authError: 'Erro de Autenticação',
      signInSubtitle: 'Faça login para experimentar o futuro do cálculo',
      continueWithGoogle: 'Continuar com Google',
      fillAllFields: 'Por favor preencha todos os campos',
      validEmailRequired: 'Por favor digite um endereço de e-mail válido',
      passwordsDoNotMatch: 'As senhas não coincidem',
      passwordMinLength: 'A senha deve ter pelo menos 6 caracteres',
      signInToContinue: 'Faça login para continuar',
      settingUpAccount: 'Bem-vindo ao Calc AI',
      signOut: 'Sair',
      anonymousCat: 'Gato Anônimo',
      guestUser: 'Usuário Convidado',
      failedToSignOut: 'Falha ao sair',
      // Additional Auth Keys
      calculatorApp: 'Aplicativo Calculadora',
      createNewAccount: 'Criar uma nova conta',
      signUpPending: 'Cadastro Pendente',
      checkEmailVerification:
        'Por favor verifique seu e-mail e clique no link de verificação para completar o registro.',
      signUp: 'Cadastrar',
      alreadyHaveAccount: 'Já tem uma conta? Fazer Login',
    },
    common: {
      error: 'Erro',
      privacyPolicy: 'Política de Privacidade',
      screenNotExist: 'Esta tela não existe.',
      lastUpdated: 'Última Atualização: 9 de Maio, 2025',
      duplicate: 'Duplicado',
      urlAlreadyAdded: 'Esta URL já foi adicionada.',
      pro: 'PRO',
      goToHomeScreen: 'Ir para a tela inicial!',
      comingSoon: '(em breve)',
      // Additional Common UI Elements
      modal: 'Modal',
    },
    premium: {
      unlockPremiumFeatures: 'Desbloquear Recursos Premium',
      premium: 'PREMIUM',
      upgradeDescription:
        'Atualize para Acesso Premium Vitalício para desbloquear funcionalidade de webhook e mais recursos premium.',
      firstUsersLifetime: 'Os Primeiros 100 Usuários Ganham Acesso Vitalício',
      toPremium: 'ao Premium! - Cadastre-se aqui',
      unlimitedCalculations: 'Cálculos Ilimitados',
      webhookIntegration: 'Integração de Webhooks',
      historySync: 'Histórico e Sincronização',
      features: {
        sendWebhooks: 'Enviar webhooks para qualquer endpoint',
        unlimitedHistory: 'Histórico de cálculos ilimitado',
        lifetimeAccess: 'Pagamento único, acesso vitalício',
      },
      oneTimePayment: 'pagamento único',
      getLifetimeAccess: 'Obter Acesso Premium Vitalício',
      modal: {
        unlockCalcAIPremium: 'Desbloquear CalcAI Premium',
        yearly: 'Anual',
        lifetime: 'Vitalício',
        onceAYear: 'Uma vez por ano',
        oneTimePayment: 'Pagamento único',
        continueWithGoogle: 'Continuar com Google',
        getYearlyAccess: 'Obter Acesso Anual',
        getLifetimeAccess: 'Obter Acesso Vitalício',
        getAccess: 'Obter Acesso',
        restorePurchase: 'RESTAURAR COMPRA',
        benefits: {
          unlimitedVoice: 'Cálculos de voz ilimitados',
          webhookIntegrations: 'Integrações de webhook (Google Sheets, Notion, etc.)',
          earlyAccess: 'Acesso antecipado a novos recursos',
          adFree: 'Experiência sem anúncios',
          exportHistory: 'Exportar histórico de cálculos',
          advancedVoice: 'Comandos de voz avançados',
          prioritySupport: 'Suporte prioritário',
        },
      },
    },
    history: {
      calculationHistory: 'Histórico de Cálculos',
      clearAll: 'Limpar Tudo',
      loadingHistory: 'Carregando histórico...',
      noHistoryYet: 'Nenhum histórico de cálculos ainda',
      historySubtext: 'Seus cálculos aparecerão aqui',
      clearAllConfirmTitle: 'Limpar Todos os Cálculos',
      clearAllConfirmMessage:
        'Tem certeza de que deseja excluir todos os cálculos? Isso não pode ser desfeito.',
      cancel: 'Cancelar',
      unknownDate: 'Data desconhecida',
      dayNames: [
        'Domingo',
        'Segunda-feira',
        'Terça-feira',
        'Quarta-feira',
        'Quinta-feira',
        'Sexta-feira',
        'Sábado',
      ],
      monthNames: [
        'Janeiro',
        'Fevereiro',
        'Março',
        'Abril',
        'Maio',
        'Junho',
        'Julho',
        'Agosto',
        'Setembro',
        'Outubro',
        'Novembro',
        'Dezembro',
      ],
    },
    editScreenInfo: {
      openCodeForScreen: 'Abra o código desta tela:',
      changeTextToUpdate:
        'Altere qualquer texto, salve o arquivo, e seu aplicativo será atualizado automaticamente.',
      tapHereIfNotUpdating:
        'Toque aqui se seu aplicativo não atualizar automaticamente após fazer alterações',
    },
    forms: {
      // Form Labels and Placeholders
      email: 'E-mail',
      password: 'Senha',
      passwordMinChars: 'Senha (mín. 6 caracteres)',
      confirmPassword: 'Confirmar Senha',
    },
    settings: {
      title: 'Configurações',
      general: {
        title: 'Geral',
        inputBehavior: 'Comportamento de Entrada',
        muteVoiceOutput: 'Silenciar Saída de Voz (M)',
        newLineOnSend: 'Nova Linha ao Enviar',
        enableVibration: 'Ativar Vibração',
        openInCalcMode: 'Abrir no Modo Calculadora',
        webhooksSection: 'Webhooks',
        sendAnswerWithoutEquation: 'Enviar somente a resposta',
        queueResultsForManualSending: 'Enviar automaticamente',
      },
      language: {
        title: 'Idioma',
        selectLanguage: 'Selecionar Idioma',
      },
      webhooks: {
        title: 'Webhooks',
        createNew: 'Criar um novo webhook',
        enterTitle: 'Digite o título do webhook (opcional)',
        enterUrl: 'Digite a URL do webhook (http:// ou https://)',
        add: 'Adicionar',
        myWebhooks: 'Meus webhooks',
        noWebhooksYet: 'Nenhum webhook adicionado ainda',
        webhookTitle: 'Título do Webhook (opcional)',
        webhookUrl: 'URL do Webhook',
        invalidUrl: 'URL Inválida',
        invalidUrlMessage: 'A URL do webhook deve ser válida e começar com http:// ou https://',
        duplicateUrl: 'URL Duplicada',
        duplicateUrlMessage: 'Esta URL de webhook já existe.',
        success: 'Sucesso',
        webhookUpdated: 'Webhook atualizado com sucesso!',
        saveError: 'Erro ao Salvar',
        couldNotSave: 'Não foi possível salvar a URL do webhook.',
      },
      bulkData: {
        title: 'Dados em Massa',
        items: 'itens',
        deleteAll: 'Deletar Tudo',
        send: 'Enviar',
        sending: 'Enviando...',
        item: 'Item',
        activateWebhook: 'Ative pelo menos um webhook para habilitar o envio',
        noActiveUrls: 'Nenhuma URL Ativa',
        activateMessage: 'Por favor ative pelo menos uma URL de webhook.',
        sendComplete: 'Envio Completo',
        successfullySentTo: 'Enviado com sucesso para',
        endpoint: 'endpoint',
        endpoints: 'endpoints',
        failedToSendTo: 'Falha ao enviar para',
        sendError: 'Erro de Envio',
        errorSending: 'Ocorreu um erro ao enviar os dados.',
        saveErrorMessage: 'Ocorreu um erro ao salvar os dados editados.',
        deleteError: 'Erro de Exclusão',
        deleteErrorMessage: 'Ocorreu um erro ao deletar o item.',
      },
    },
  },
  it: {
    mainApp: {
      speechNotSupported: 'Riconoscimento vocale non supportato in questo browser.',
      permissionRequired: 'Permesso richiesto',
      microphonePermissionRequired: "È richiesta l'autorizzazione del microfono.",
      invalidUrl: 'URL Non Valido',
      invalidUrlMessage: "L'URL del webhook deve iniziare con http:// o https://",
      duplicate: 'Duplicato',
      duplicateUrlMessage: 'Questo URL è già aggiunto.',
      noData: 'Nessun Dato',
      noDataMessage: 'Non ci sono dati memorizzati da inviare.',
      noActiveUrls: 'Nessun URL Attivo',
      noActiveUrlsMessage: 'Per favore attiva almeno un URL webhook nelle impostazioni.',
      bulkSendError: 'Errore Invio di Massa',
      bulkSendErrorMessage:
        'Si è verificato un errore imprevisto durante il processo di invio di massa.',
      activeWebhooks: 'WEBHOOKS ATTIVI',
      dataQueue: 'CODA DATI',
      voiceMuted: 'Voce disattivata',
      voiceUnmuted: 'Voce attivata',
      couldNotSendData: 'Impossibile inviare i dati',
      couldNotSaveSettings: 'Impossibile salvare le impostazioni',
      answerCopiedToClipboard: 'Risposta copiata negli appunti',
      bulkSendComplete: 'Invio di Massa Completato',
      // Empty States and Instructions
      pressSpaceToRecord: 'Premi SPAZIO per iniziare la registrazione',
      pressSendToConfirm: 'Premi INVIA per confermare il calcolo',
      useWebhookForSheets: 'Usa WEBHOOK per inviare risultati a Google Sheets',
      pressRecordIcon: "Premi l'icona REGISTRA per iniziare la registrazione",
      useWebhookToSend: 'Usa WEBHOOK per inviare risultati',
      resetCtrlBackspace: 'Ripristina (Ctrl+Backspace)',
      none: 'Nessuno',
      // Math and Speech Error Messages
      noEquationDetected: 'Nessuna Equazione Rilevata',
      mathErrors: {
        sorryTryAgain: 'Scusa, riprova',
        error: 'Errore',
        calculationFailed: 'Calcolo fallito',
        invalidExpression: 'Espressione non valida',
      },
      speechErrors: {
        recognitionFailed: 'Riconoscimento vocale fallito',
        microphoneError: 'Errore del microfono',
        noSpeechDetected: 'Nessun parlato rilevato',
        networkError: 'Errore di rete durante il riconoscimento',
      },
    },
    auth: {
      error: 'Errore',
      authError: 'Errore di Autenticazione',
      signInSubtitle: 'Accedi per sperimentare il futuro del calcolo',
      continueWithGoogle: 'Continua con Google',
      fillAllFields: 'Per favore compila tutti i campi',
      validEmailRequired: 'Per favore inserisci un indirizzo email valido',
      passwordsDoNotMatch: 'Le password non corrispondono',
      passwordMinLength: 'La password deve essere di almeno 6 caratteri',
      signInToContinue: 'Accedi per continuare',
      settingUpAccount: 'Benvenuto su Calc AI',
      signOut: 'Esci',
      anonymousCat: 'Gatto Anonimo',
      guestUser: 'Utente Ospite',
      failedToSignOut: 'Impossibile disconnettersi',
      // Additional Auth Keys
      calculatorApp: 'App Calcolatrice',
      createNewAccount: 'Crea un nuovo account',
      signUpPending: 'Registrazione in Sospeso',
      checkEmailVerification:
        'Per favore controlla la tua email e clicca sul link di verifica per completare la registrazione.',
      signUp: 'Registrati',
      alreadyHaveAccount: 'Hai già un account? Accedi',
    },
    common: {
      error: 'Errore',
      privacyPolicy: 'Informativa sulla Privacy',
      screenNotExist: 'Questa schermata non esiste.',
      lastUpdated: 'Ultimo Aggiornamento: 9 Maggio 2025',
      duplicate: 'Duplicato',
      urlAlreadyAdded: 'Questo URL è già stato aggiunto.',
      pro: 'PRO',
      goToHomeScreen: 'Vai alla schermata principale!',
      comingSoon: '(prossimamente)',
      // Additional Common UI Elements
      modal: 'Modale',
    },
    premium: {
      unlockPremiumFeatures: 'Sblocca Funzionalità Premium',
      premium: 'PREMIUM',
      upgradeDescription:
        "Aggiorna all'Accesso Premium a Vita per sbloccare la funzionalità webhook e altre funzionalità premium.",
      firstUsersLifetime: 'I Primi 100 Utenti Ottengono Accesso a Vita',
      toPremium: 'a Premium! - Registrati qui',
      unlimitedCalculations: 'Calcoli Illimitati',
      webhookIntegration: 'Integrazione Webhooks',
      historySync: 'Cronologia e Sincronizzazione',
      features: {
        sendWebhooks: 'Invia webhooks a qualsiasi endpoint',
        unlimitedHistory: 'Cronologia calcoli illimitata',
        lifetimeAccess: 'Pagamento unico, accesso a vita',
      },
      oneTimePayment: 'pagamento unico',
      getLifetimeAccess: 'Ottieni Accesso Premium a Vita',
      modal: {
        unlockCalcAIPremium: 'Sblocca CalcAI Premium',
        yearly: 'Annuale',
        lifetime: 'A Vita',
        onceAYear: "Una volta all'anno",
        oneTimePayment: 'Pagamento unico',
        continueWithGoogle: 'Continua con Google',
        getYearlyAccess: 'Ottieni Accesso Annuale',
        getLifetimeAccess: 'Ottieni Accesso a Vita',
        getAccess: 'Ottieni Accesso',
        restorePurchase: 'RIPRISTINA ACQUISTO',
        benefits: {
          unlimitedVoice: 'Calcoli vocali illimitati',
          webhookIntegrations: 'Integrazioni webhook (Google Sheets, Notion, etc.)',
          earlyAccess: 'Accesso anticipato alle nuove funzionalità',
          adFree: 'Esperienza senza pubblicità',
          exportHistory: 'Esporta cronologia calcoli',
          advancedVoice: 'Comandi vocali avanzati',
          prioritySupport: 'Supporto prioritario',
        },
      },
    },
    history: {
      calculationHistory: 'Cronologia Calcoli',
      clearAll: 'Cancella Tutto',
      loadingHistory: 'Caricamento cronologia...',
      noHistoryYet: 'Nessuna cronologia calcoli ancora',
      historySubtext: 'I tuoi calcoli appariranno qui',
      clearAllConfirmTitle: 'Cancella Tutti i Calcoli',
      clearAllConfirmMessage:
        'Sei sicuro di voler eliminare tutti i calcoli? Questa azione non può essere annullata.',
      cancel: 'Annulla',
      unknownDate: 'Data sconosciuta',
      dayNames: ['Domenica', 'Lunedì', 'Martedì', 'Mercoledì', 'Giovedì', 'Venerdì', 'Sabato'],
      monthNames: [
        'Gennaio',
        'Febbraio',
        'Marzo',
        'Aprile',
        'Maggio',
        'Giugno',
        'Luglio',
        'Agosto',
        'Settembre',
        'Ottobre',
        'Novembre',
        'Dicembre',
      ],
    },
    editScreenInfo: {
      openCodeForScreen: 'Apri il codice di questa schermata:',
      changeTextToUpdate:
        'Cambia qualsiasi testo, salva il file, e la tua app si aggiornerà automaticamente.',
      tapHereIfNotUpdating:
        'Tocca qui se la tua app non si aggiorna automaticamente dopo aver fatto modifiche',
    },
    forms: {
      // Form Labels and Placeholders
      email: 'Email',
      password: 'Password',
      passwordMinChars: 'Password (min. 6 caratteri)',
      confirmPassword: 'Conferma Password',
    },
    settings: {
      title: 'Impostazioni',
      general: {
        title: 'Generale',
        inputBehavior: 'Comportamento Input',
        muteVoiceOutput: 'Silenzia Uscita Vocale (M)',
        newLineOnSend: "Nuova Riga all'Invio",
        enableVibration: 'Abilita Vibrazione',
        openInCalcMode: 'Apri in Modalità Calcolatrice',
        webhooksSection: 'Webhooks',
        sendAnswerWithoutEquation: 'Inviare soltanto la risposta',
        queueResultsForManualSending: 'Inviare automaticamente',
      },
      language: {
        title: 'Lingua',
        selectLanguage: 'Seleziona Lingua',
      },
      webhooks: {
        title: 'Webhooks',
        createNew: 'Crea un nuovo webhook',
        enterTitle: 'Inserisci titolo webhook (opzionale)',
        enterUrl: 'Inserisci URL webhook (http:// o https://)',
        add: 'Aggiungi',
        myWebhooks: 'I miei webhooks',
        noWebhooksYet: 'Nessun webhook aggiunto ancora',
        webhookTitle: 'Titolo Webhook (opzionale)',
        webhookUrl: 'URL Webhook',
        invalidUrl: 'URL Non Valido',
        invalidUrlMessage: "L'URL del webhook deve essere valido e iniziare con http:// o https://",
        duplicateUrl: 'URL Duplicato',
        duplicateUrlMessage: 'Questo URL webhook esiste già.',
        success: 'Successo',
        webhookUpdated: 'Webhook aggiornato con successo!',
        saveError: 'Errore di Salvataggio',
        couldNotSave: "Impossibile salvare l'URL del webhook.",
      },
      bulkData: {
        title: 'Dati di Massa',
        items: 'elementi',
        deleteAll: 'Elimina Tutto',
        send: 'Invia',
        sending: 'Invio in corso...',
        item: 'Elemento',
        activateWebhook: "Attiva almeno un webhook per abilitare l'invio",
        noActiveUrls: 'Nessun URL Attivo',
        activateMessage: 'Per favore attiva almeno un URL webhook.',
        sendComplete: 'Invio Completato',
        successfullySentTo: 'Inviato con successo a',
        endpoint: 'endpoint',
        endpoints: 'endpoints',
        failedToSendTo: 'Invio fallito a',
        sendError: 'Errore di Invio',
        errorSending: "Si è verificato un errore durante l'invio dei dati.",
        saveErrorMessage: 'Si è verificato un errore durante il salvataggio dei dati modificati.',
        deleteError: 'Errore di Eliminazione',
        deleteErrorMessage: "Si è verificato un errore durante l'eliminazione dell'elemento.",
      },
    },
  },
};

// Define type for math patterns
export interface LanguagePatterns {
  numbers: { [key: string]: string };
  operations: {
    addition: string[];
    subtraction: string[];
    multiplication: string[];
    division: string[];
    percentage: string[];
    percentOf: string[];
    power: string[];
    sqrt: string[];
    parentheses: {
      open: string[];
      close: string[];
    };
    decimal: string[];
  };
  specificPhrases: {
    addTo: string;
    subtractFrom: string;
    multiplyBy: string;
    divideBy: string;
  };
}

// Language patterns for speech-to-math conversion
export const LANGUAGE_PATTERNS: { [key: string]: LanguagePatterns } = {
  en: {
    numbers: {
      zero: '0',
      one: '1',
      two: '2',
      three: '3',
      four: '4',
      five: '5',
      six: '6',
      seven: '7',
      eight: '8',
      nine: '9',
      ten: '10',
      eleven: '11',
      twelve: '12',
      thirteen: '13',
      fourteen: '14',
      fifteen: '15',
      sixteen: '16',
      seventeen: '17',
      eighteen: '18',
      nineteen: '19',
      twenty: '20',
      thirty: '30',
      forty: '40',
      fifty: '50',
      sixty: '60',
      seventy: '70',
      eighty: '80',
      ninety: '90',
      hundred: '100',
      thousand: '1000',
      million: '1000000',
      billion: '1000000000',
      trillion: '1000000000000',
    },
    operations: {
      addition: ['plus', 'add', 'added', 'adding', 'and', 'sum', 'total', 'combine', 'combined'],
      subtraction: [
        'minus',
        'subtract',
        'subtracted',
        'subtracting',
        'less',
        'take away',
        'remove',
        'removed',
        'decrease',
        'decreased',
      ],
      multiplication: [
        'times',
        'multiplied by',
        'multiply',
        'multiplying',
        'x',
        'product',
        'product of',
      ],
      division: ['divided by', 'divided', 'divide', 'dividing', 'over', 'split', 'split by'],
      percentage: ['percent', 'percentage', '%'],
      percentOf: ['percent of', 'percentage of', '% of'],
      power: [
        'power',
        'raised to',
        'to the power of',
        'to the power',
        'squared',
        'cubed',
        'exponent',
      ],
      sqrt: ['square root of', 'root of', 'square root', 'root'],
      parentheses: {
        open: ['open parenthesis', 'left parenthesis', 'open bracket'],
        close: ['close parenthesis', 'right parenthesis', 'close bracket'],
      },
      decimal: ['point', 'dot', 'decimal', 'comma'],
    },
    specificPhrases: {
      addTo: String.raw`add (\d+(?:\.\d+)?) to (\d+(?:\.\d+)?)`,
      subtractFrom: String.raw`subtract (\d+(?:\.\d+)?) from (\d+(?:\.\d+)?)`,
      multiplyBy: String.raw`(multiply|multiplied) (\d+(?:\.\d+)?) by (\d+(?:\.\d+)?)`,
      divideBy: String.raw`(divide|divided) (\d+(?:\.\d+)?) by (\d+(?:\.\d+)?)`,
    },
  },
  es: {
    numbers: {
      cero: '0',
      uno: '1',
      dos: '2',
      tres: '3',
      cuatro: '4',
      cinco: '5',
      seis: '6',
      siete: '7',
      ocho: '8',
      nueve: '9',
      diez: '10',
      once: '11',
      doce: '12',
      trece: '13',
      catorce: '14',
      quince: '15',
      dieciséis: '16',
      diecisiete: '17',
      dieciocho: '18',
      diecinueve: '19',
      veinte: '20',
      treinta: '30',
      cuarenta: '40',
      cincuenta: '50',
      sesenta: '60',
      setenta: '70',
      ochenta: '80',
      noventa: '90',
      cien: '100',
      mil: '1000',
      millón: '1000000',
      'mil millones': '1000000000',
      billón: '1000000000000',
    },
    operations: {
      addition: [
        'más',
        'sumar',
        'suma',
        'sumado',
        'y',
        'añadir',
        'añade',
        'añadido',
        'agregar',
        'agrega',
        'agregado',
      ],
      subtraction: [
        'menos',
        'restar',
        'resta',
        'restado',
        'quitar',
        'quita',
        'quitado',
        'sacar',
        'saca',
        'sacado',
        'disminuir',
        'disminuye',
        'disminuido',
      ],
      multiplication: [
        'por',
        'multiplicado por',
        'multiplicar',
        'multiplica',
        'veces',
        'x',
        'producto',
        'producto de',
      ],
      division: ['dividido por', 'dividir', 'divide', 'dividido', 'sobre', 'entre'],
      percentage: ['por ciento', 'porciento', 'porcentaje', '%'],
      percentOf: ['por ciento de', 'porciento de', 'porcentaje de'],
      power: [
        'elevado a',
        'elevado',
        'a la potencia de',
        'a la potencia',
        'al cuadrado',
        'al cubo',
        'potencia',
        'exponente',
      ],
      sqrt: ['raíz cuadrada de', 'raíz de', 'raíz cuadrada', 'raíz'],
      parentheses: {
        open: ['abrir paréntesis', 'paréntesis izquierdo', 'abrir corchete'],
        close: ['cerrar paréntesis', 'paréntesis derecho', 'cerrar corchete'],
      },
      decimal: ['punto', 'coma', 'decimal'],
    },
    specificPhrases: {
      addTo: String.raw`sumar (\d+(?:\.\d+)?) a (\d+(?:\.\d+)?)`,
      subtractFrom: String.raw`restar (\d+(?:\.\d+)?) de (\d+(?:\.\d+)?)`,
      multiplyBy: String.raw`(multiplicar|multiplicado) (\d+(?:\.\d+)?) por (\d+(?:\.\d+)?)`,
      divideBy: String.raw`(dividir|dividido) (\d+(?:\.\d+)?) por (\d+(?:\.\d+)?)`,
    },
  },
  fr: {
    numbers: {
      zéro: '0',
      un: '1',
      deux: '2',
      trois: '3',
      quatre: '4',
      cinq: '5',
      six: '6',
      sept: '7',
      huit: '8',
      neuf: '9',
      dix: '10',
      onze: '11',
      douze: '12',
      treize: '13',
      quatorze: '14',
      quinze: '15',
      seize: '16',
      'dix-sept': '17',
      'dix-huit': '18',
      'dix-neuf': '19',
      vingt: '20',
      trente: '30',
      quarante: '40',
      cinquante: '50',
      soixante: '60',
      'soixante-dix': '70',
      'quatre-vingts': '80',
      'quatre-vingt-dix': '90',
      cent: '100',
      mille: '1000',
      million: '1000000',
      milliard: '1000000000',
      trillion: '1000000000000',
    },
    operations: {
      addition: [
        'plus',
        'ajouter',
        'ajoute',
        'ajouté',
        'et',
        'additionner',
        'additionne',
        'additionné',
        'somme',
        'sommer',
        'somme de',
        'rajouter',
        'rajoute',
        'rajouté',
      ],
      subtraction: [
        'moins',
        'soustraire',
        'soustrait',
        'soustraction',
        'retirer',
        'retire',
        'retiré',
        'enlever',
        'enlève',
        'enlevé',
        'ôter',
        'ôte',
        'ôté',
        'diminuer',
        'diminue',
        'diminué',
      ],
      multiplication: [
        'fois',
        'multiplié par',
        'multiplier',
        'multiplie',
        'multiplication',
        'x',
        'par',
        'produit',
        'produit de',
      ],
      division: [
        'divisé',
        'divisé par',
        'diviser',
        'divise',
        'division',
        'sur',
        'divisée par',
        'divisée',
      ],
      percentage: ['pour cent', 'pourcent', 'pourcentage', '%'],
      percentOf: ['pour cent de', 'pourcent de', 'pourcentage de'],
      power: [
        'puissance',
        'élevé à',
        'élevé',
        'à la puissance de',
        'à la puissance',
        'au carré',
        'au cube',
        'exposant',
      ],
      sqrt: ['racine carrée de', 'racine de', 'racine carrée', 'racine'],
      parentheses: {
        open: ['ouvrir parenthèse', 'parenthèse gauche', 'ouvrir crochet', 'ouvre parenthèse'],
        close: ['fermer parenthèse', 'parenthèse droite', 'fermer crochet', 'ferme parenthèse'],
      },
      decimal: ['virgule', 'point', 'décimal', 'décimale'],
    },
    specificPhrases: {
      addTo: String.raw`(ajouter|ajoute|additionner|additionne) (\d+(?:\.\d+)?) (à|a) (\d+(?:\.\d+)?)`,
      subtractFrom: String.raw`(soustraire|soustrait|retirer|retire|enlever|enlève|ôter|ôte) (\d+(?:\.\d+)?) (de|à|a) (\d+(?:\.\d+)?)`,
      multiplyBy: String.raw`(multiplier|multiplie|multiplié) (\d+(?:\.\d+)?) par (\d+(?:\.\d+)?)`,
      divideBy: String.raw`(diviser|divise|divisé|divisée) (\d+(?:\.\d+)?) par (\d+(?:\.\d+)?)`,
    },
  },
  de: {
    numbers: {
      null: '0',
      eins: '1',
      zwei: '2',
      drei: '3',
      vier: '4',
      fünf: '5',
      sechs: '6',
      sieben: '7',
      acht: '8',
      neun: '9',
      zehn: '10',
      elf: '11',
      zwölf: '12',
      dreizehn: '13',
      vierzehn: '14',
      fünfzehn: '15',
      sechzehn: '16',
      siebzehn: '17',
      achtzehn: '18',
      neunzehn: '19',
      zwanzig: '20',
      dreißig: '30',
      vierzig: '40',
      fünfzig: '50',
      sechzig: '60',
      siebzig: '70',
      achtzig: '80',
      neunzig: '90',
      hundert: '100',
      tausend: '1000',
      million: '1000000',
      milliarde: '1000000000',
      trillion: '1000000000000',
    },
    operations: {
      addition: [
        'plus',
        'addieren',
        'addiere',
        'addiert',
        'und',
        'hinzufügen',
        'hinzufüge',
        'hinzugefügt',
        'dazu',
        'summieren',
        'summe',
      ],
      subtraction: [
        'minus',
        'subtrahieren',
        'subtrahiere',
        'subtrahiert',
        'weniger',
        'abziehen',
        'ziehe ab',
        'abgezogen',
        'wegnehmen',
        'nimm weg',
      ],
      multiplication: [
        'mal',
        'multipliziert mit',
        'multiplizieren',
        'multipliziere',
        'x',
        'produkt',
        'produkt von',
      ],
      division: ['geteilt durch', 'dividiert durch', 'teilen', 'teile', 'über', 'durch'],
      percentage: ['prozent', 'vom hundert', '%'],
      percentOf: ['prozent von', 'prozent des'],
      power: ['hoch', 'zur potenz', 'zur potenz von', 'quadrat', 'kubik', 'potenz', 'exponent'],
      sqrt: ['quadratwurzel von', 'wurzel von', 'quadratwurzel', 'wurzel'],
      parentheses: {
        open: ['klammer auf', 'linke klammer', 'öffnende klammer'],
        close: ['klammer zu', 'rechte klammer', 'schließende klammer'],
      },
      decimal: ['komma', 'punkt', 'dezimal'],
    },
    specificPhrases: {
      addTo: String.raw`addiere (\d+(?:\.\d+)?) zu (\d+(?:\.\d+)?)`,
      subtractFrom: String.raw`subtrahiere (\d+(?:\.\d+)?) von (\d+(?:\.\d+)?)`,
      multiplyBy: String.raw`(multipliziere|multipliziert) (\d+(?:\.\d+)?) mit (\d+(?:\.\d+)?)`,
      divideBy: String.raw`(teile|geteilt) (\d+(?:\.\d+)?) durch (\d+(?:\.\d+)?)`,
    },
  },
  pt: {
    numbers: {
      zero: '0',
      um: '1',
      dois: '2',
      três: '3',
      quatro: '4',
      cinco: '5',
      seis: '6',
      sete: '7',
      oito: '8',
      nove: '9',
      dez: '10',
      onze: '11',
      doze: '12',
      treze: '13',
      quatorze: '14',
      quinze: '15',
      dezesseis: '16',
      dezessete: '17',
      dezoito: '18',
      dezenove: '19',
      vinte: '20',
      trinta: '30',
      quarenta: '40',
      cinquenta: '50',
      sessenta: '60',
      setenta: '70',
      oitenta: '80',
      noventa: '90',
      cem: '100',
      mil: '1000',
      milhão: '1000000',
      bilhão: '1000000000',
      trilhão: '1000000000000',
    },
    operations: {
      addition: [
        'mais',
        'somar',
        'soma',
        'somado',
        'e',
        'adicionar',
        'adiciona',
        'adicionado',
        'acrescentar',
        'acrescenta',
        'acrescentado',
      ],
      subtraction: [
        'menos',
        'subtrair',
        'subtrai',
        'subtraído',
        'tirar',
        'tira',
        'tirado',
        'retirar',
        'retira',
        'retirado',
        'diminuir',
        'diminui',
        'diminuído',
      ],
      multiplication: [
        'vezes',
        'multiplicado por',
        'multiplicar',
        'multiplica',
        'x',
        'produto',
        'produto de',
      ],
      division: ['dividido por', 'dividir', 'divide', 'dividido', 'sobre', 'por'],
      percentage: ['por cento', 'porcento', 'percentagem', '%'],
      percentOf: ['por cento de', 'porcento de', 'percentagem de'],
      power: [
        'elevado a',
        'elevado',
        'à potência de',
        'à potência',
        'ao quadrado',
        'ao cubo',
        'potência',
        'expoente',
      ],
      sqrt: ['raiz quadrada de', 'raiz de', 'raiz quadrada', 'raiz'],
      parentheses: {
        open: ['abrir parênteses', 'parênteses esquerdo', 'abrir colchetes'],
        close: ['fechar parênteses', 'parênteses direito', 'fechar colchetes'],
      },
      decimal: ['vírgula', 'ponto', 'decimal'],
    },
    specificPhrases: {
      addTo: String.raw`somar (\d+(?:\.\d+)?) a (\d+(?:\.\d+)?)`,
      subtractFrom: String.raw`subtrair (\d+(?:\.\d+)?) de (\d+(?:\.\d+)?)`,
      multiplyBy: String.raw`(multiplicar|multiplicado) (\d+(?:\.\d+)?) por (\d+(?:\.\d+)?)`,
      divideBy: String.raw`(dividir|dividido) (\d+(?:\.\d+)?) por (\d+(?:\.\d+)?)`,
    },
  },
  it: {
    numbers: {
      zero: '0',
      uno: '1',
      due: '2',
      tre: '3',
      quattro: '4',
      cinque: '5',
      sei: '6',
      sette: '7',
      otto: '8',
      nove: '9',
      dieci: '10',
      undici: '11',
      dodici: '12',
      tredici: '13',
      quattordici: '14',
      quindici: '15',
      sedici: '16',
      diciassette: '17',
      diciotto: '18',
      diciannove: '19',
      venti: '20',
      trenta: '30',
      quaranta: '40',
      cinquanta: '50',
      sessanta: '60',
      settanta: '70',
      ottanta: '80',
      novanta: '90',
      cento: '100',
      mille: '1000',
      milione: '1000000',
      miliardo: '1000000000',
      trillione: '1000000000000',
    },
    operations: {
      addition: [
        'più',
        'sommare',
        'somma',
        'sommato',
        'e',
        'aggiungere',
        'aggiungi',
        'aggiunto',
        'addizionare',
        'addiziona',
        'addizionato',
      ],
      subtraction: [
        'meno',
        'sottrarre',
        'sottrai',
        'sottratto',
        'togliere',
        'togli',
        'tolto',
        'levare',
        'leva',
        'levato',
        'diminuire',
        'diminuisci',
        'diminuito',
      ],
      multiplication: [
        'per',
        'moltiplicato per',
        'moltiplicare',
        'moltiplica',
        'x',
        'prodotto',
        'prodotto di',
      ],
      division: ['diviso per', 'dividere', 'dividi', 'diviso', 'sopra', 'fratto'],
      percentage: ['per cento', 'percento', 'percentuale', '%'],
      percentOf: ['per cento di', 'percento di', 'percentuale di'],
      power: [
        'elevato a',
        'elevato',
        'alla potenza di',
        'alla potenza',
        'al quadrato',
        'al cubo',
        'potenza',
        'esponente',
      ],
      sqrt: ['radice quadrata di', 'radice di', 'radice quadrata', 'radice'],
      parentheses: {
        open: ['apri parentesi', 'parentesi sinistra', 'apri quadre'],
        close: ['chiudi parentesi', 'parentesi destra', 'chiudi quadre'],
      },
      decimal: ['virgola', 'punto', 'decimale'],
    },
    specificPhrases: {
      addTo: String.raw`sommare (\d+(?:\.\d+)?) a (\d+(?:\.\d+)?)`,
      subtractFrom: String.raw`sottrarre (\d+(?:\.\d+)?) da (\d+(?:\.\d+)?)`,
      multiplyBy: String.raw`(moltiplicare|moltiplicato) (\d+(?:\.\d+)?) per (\d+(?:\.\d+)?)`,
      divideBy: String.raw`(dividere|diviso) (\d+(?:\.\d+)?) per (\d+(?:\.\d+)?)`,
    },
  },
};
