export interface Language {
  code: string;
  name: string;
  nativeName: string;
  flag: string;
}

export const SUPPORTED_LANGUAGES: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇺🇸' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇵🇹' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano', flag: '🇮🇹' },
];

export const DEFAULT_LANGUAGE = 'en';

export type TranslationKey = string;

export interface Translations {
  [key: string]: string | Translations;
}

export const TRANSLATIONS: Record<string, Translations> = {
  en: {
    settings: {
      title: 'Settings',
      general: {
        title: 'General',
        inputBehavior: 'Input Behavior',
        muteVoiceOutput: 'Mute Voice Output (M)',
        newLineOnSend: 'New Line on Send',
        enableVibration: 'Enable Vibration',
        openInCalcMode: 'Open in Calculator Mode',
        webhooksSection: 'Webhooks',
        sendAnswerWithoutEquation: 'Send Answer Without Equation',
        queueResultsForManualSending: 'Queue Results for Manual Sending',
      },
      language: {
        title: 'Language',
        selectLanguage: 'Select Language',
      },
      webhooks: {
        title: 'Webhooks',
        createNew: 'Create a new webhook',
        enterTitle: 'Enter webhook title (optional)',
        enterUrl: 'Enter webhook URL (http:// or https://)',
        add: 'Add',
        myWebhooks: 'My webhooks',
        noWebhooksYet: 'No webhooks added yet',
        webhookTitle: 'Webhook Title (optional)',
        webhookUrl: 'Webhook URL',
        invalidUrl: 'Invalid URL',
        invalidUrlMessage: 'Webhook URL must be a valid URL starting with http:// or https://',
        duplicateUrl: 'Duplicate URL',
        duplicateUrlMessage: 'This webhook URL already exists.',
        success: 'Success',
        webhookUpdated: 'Webhook updated successfully!',
        saveError: 'Save Error',
        couldNotSave: 'Could not save the webhook URL.',
      },
      bulkData: {
        title: 'Bulk Data',
        items: 'items',
        deleteAll: 'Delete All',
        send: 'Send',
        sending: 'Sending...',
        item: 'Item',
        activateWebhook: 'Activate at least one webhook to enable sending',
        noActiveUrls: 'No Active URLs',
        activateMessage: 'Please activate at least one webhook URL.',
        sendComplete: 'Send Complete',
        successfullySentTo: 'Successfully sent to',
        endpoint: 'endpoint',
        endpoints: 'endpoints',
        failedToSendTo: 'Failed to send to',
        sendError: 'Send Error',
        errorSending: 'An error occurred while sending the data.',
        saveErrorMessage: 'An error occurred while saving the edited data.',
        deleteError: 'Delete Error',
        deleteErrorMessage: 'An error occurred while deleting the item.',
      },
      auth: {
        signInToContinue: 'Sign in to continue',
        continueWithGoogle: 'Continue with Google',
        signOut: 'Sign Out',
        anonymousCat: 'Anonymous Cat',
        guestUser: 'Guest User',
        firstUsersLifetime: 'First 100 Users Get Lifetime Access',
        toPremium: 'to Premium! - Sign up here',
        unlimitedCalculations: 'Unlimited Calculations',
        webhookIntegration: 'Webhook Integration',
        historySync: 'History & Sync',
        comingSoon: '(soon)',
        authError: 'Auth Error',
        error: 'Error',
        failedToSignOut: 'Failed to sign out',
      },
      common: {
        duplicate: 'Duplicate',
        urlAlreadyAdded: 'This URL is already added.',
        privacyPolicy: 'Privacy Policy',
        pro: 'PRO',
        beta: 'BETA',
      },
    },
  },
  es: {
    settings: {
      title: 'Configuración',
      general: {
        title: 'General',
        inputBehavior: 'Comportamiento de Entrada',
        muteVoiceOutput: 'Silenciar Salida de Voz (M)',
        newLineOnSend: 'Nueva Línea al Enviar',
        enableVibration: 'Habilitar Vibración',
        openInCalcMode: 'Abrir en Modo Calculadora',
        webhooksSection: 'Webhooks',
        sendAnswerWithoutEquation: 'Enviar Respuesta Sin Ecuación',
        queueResultsForManualSending: 'Poner Resultados en Cola para Envío Manual',
      },
      language: {
        title: 'Idioma',
        selectLanguage: 'Seleccionar Idioma',
      },
      webhooks: {
        title: 'Webhooks',
        createNew: 'Crear un nuevo webhook',
        enterTitle: 'Ingrese título del webhook (opcional)',
        enterUrl: 'Ingrese URL del webhook (http:// o https://)',
        add: 'Añadir',
        myWebhooks: 'Mis webhooks',
        noWebhooksYet: 'No se han añadido webhooks aún',
        webhookTitle: 'Título del Webhook (opcional)',
        webhookUrl: 'URL del Webhook',
        invalidUrl: 'URL Inválida',
        invalidUrlMessage: 'La URL del webhook debe ser válida y comenzar con http:// o https://',
        duplicateUrl: 'URL Duplicada',
        duplicateUrlMessage: 'Esta URL del webhook ya existe.',
        success: 'Éxito',
        webhookUpdated: '¡Webhook actualizado exitosamente!',
        saveError: 'Error al Guardar',
        couldNotSave: 'No se pudo guardar la URL del webhook.',
      },
      bulkData: {
        title: 'Datos Masivos',
        items: 'elementos',
        deleteAll: 'Eliminar Todo',
        send: 'Enviar',
        sending: 'Enviando...',
        item: 'Elemento',
        activateWebhook: 'Active al menos un webhook para habilitar el envío',
        noActiveUrls: 'No hay URLs Activas',
        activateMessage: 'Por favor active al menos una URL de webhook.',
        sendComplete: 'Envío Completo',
        successfullySentTo: 'Enviado exitosamente a',
        endpoint: 'endpoint',
        endpoints: 'endpoints',
        failedToSendTo: 'Error al enviar a',
        sendError: 'Error de Envío',
        errorSending: 'Ocurrió un error al enviar los datos.',
        saveErrorMessage: 'Ocurrió un error al guardar los datos editados.',
        deleteError: 'Error de Eliminación',
        deleteErrorMessage: 'Ocurrió un error al eliminar el elemento.',
      },
      auth: {
        signInToContinue: 'Inicie sesión para continuar',
        continueWithGoogle: 'Continuar con Google',
        signOut: 'Cerrar Sesión',
        anonymousCat: 'Gato Anónimo',
        guestUser: 'Usuario Invitado',
        firstUsersLifetime: 'Los Primeros 100 Usuarios Obtienen Acceso de Por Vida',
        toPremium: '¡a Premium! - Regístrese aquí',
        unlimitedCalculations: 'Cálculos Ilimitados',
        webhookIntegration: 'Integración de Webhooks',
        historySync: 'Historial y Sincronización',
        comingSoon: '(próximamente)',
        authError: 'Error de Autenticación',
        error: 'Error',
        failedToSignOut: 'Error al cerrar sesión',
      },
      common: {
        duplicate: 'Duplicado',
        urlAlreadyAdded: 'Esta URL ya fue añadida.',
        privacyPolicy: 'Política de Privacidad',
        pro: 'PRO',
        beta: 'BETA',
      },
    },
  },
  fr: {
    settings: {
      title: 'Paramètres',
      general: {
        title: 'Général',
        inputBehavior: 'Comportement de Saisie',
        muteVoiceOutput: 'Couper la Sortie Vocale (M)',
        newLineOnSend: 'Nouvelle Ligne à l\'Envoi',
        enableVibration: 'Activer la Vibration',
        openInCalcMode: 'Ouvrir en Mode Calculatrice',
        webhooksSection: 'Webhooks',
        sendAnswerWithoutEquation: 'Envoyer la Réponse Sans Équation',
        queueResultsForManualSending: 'Mettre les Résultats en File pour Envoi Manuel',
      },
      language: {
        title: 'Langue',
        selectLanguage: 'Sélectionner la Langue',
      },
      webhooks: {
        title: 'Webhooks',
        createNew: 'Créer un nouveau webhook',
        enterTitle: 'Entrez le titre du webhook (optionnel)',
        enterUrl: 'Entrez l\'URL du webhook (http:// ou https://)',
        add: 'Ajouter',
        myWebhooks: 'Mes webhooks',
        noWebhooksYet: 'Aucun webhook ajouté pour le moment',
        webhookTitle: 'Titre du Webhook (optionnel)',
        webhookUrl: 'URL du Webhook',
        invalidUrl: 'URL Invalide',
        invalidUrlMessage: 'L\'URL du webhook doit être valide et commencer par http:// ou https://',
        duplicateUrl: 'URL Dupliquée',
        duplicateUrlMessage: 'Cette URL de webhook existe déjà.',
        success: 'Succès',
        webhookUpdated: 'Webhook mis à jour avec succès !',
        saveError: 'Erreur de Sauvegarde',
        couldNotSave: 'Impossible de sauvegarder l\'URL du webhook.',
      },
      bulkData: {
        title: 'Données en Lot',
        items: 'éléments',
        deleteAll: 'Tout Supprimer',
        send: 'Envoyer',
        sending: 'Envoi en cours...',
        item: 'Élément',
        activateWebhook: 'Activez au moins un webhook pour permettre l\'envoi',
        noActiveUrls: 'Aucune URL Active',
        activateMessage: 'Veuillez activer au moins une URL de webhook.',
        sendComplete: 'Envoi Terminé',
        successfullySentTo: 'Envoyé avec succès à',
        endpoint: 'endpoint',
        endpoints: 'endpoints',
        failedToSendTo: 'Échec de l\'envoi vers',
        sendError: 'Erreur d\'Envoi',
        errorSending: 'Une erreur s\'est produite lors de l\'envoi des données.',
        saveErrorMessage: 'Une erreur s\'est produite lors de la sauvegarde des données modifiées.',
        deleteError: 'Erreur de Suppression',
        deleteErrorMessage: 'Une erreur s\'est produite lors de la suppression de l\'élément.',
      },
      auth: {
        signInToContinue: 'Connectez-vous pour continuer',
        continueWithGoogle: 'Continuer avec Google',
        signOut: 'Se Déconnecter',
        anonymousCat: 'Chat Anonyme',
        guestUser: 'Utilisateur Invité',
        firstUsersLifetime: 'Les 100 Premiers Utilisateurs Obtiennent un Accès à Vie',
        toPremium: 'à Premium ! - Inscrivez-vous ici',
        unlimitedCalculations: 'Calculs Illimités',
        webhookIntegration: 'Intégration de Webhooks',
        historySync: 'Historique et Synchronisation',
        comingSoon: '(bientôt)',
        authError: 'Erreur d\'Authentification',
        error: 'Erreur',
        failedToSignOut: 'Échec de la déconnexion',
      },
      common: {
        duplicate: 'Dupliquer',
        urlAlreadyAdded: 'Cette URL a déjà été ajoutée.',
        privacyPolicy: 'Politique de Confidentialité',
        pro: 'PRO',
        beta: 'BETA',
      },
    },
  },
  de: {
    settings: {
      title: 'Einstellungen',
      general: {
        title: 'Allgemein',
        inputBehavior: 'Eingabeverhalten',
        muteVoiceOutput: 'Sprachausgabe Stummschalten (M)',
        newLineOnSend: 'Neue Zeile beim Senden',
        enableVibration: 'Vibration Aktivieren',
        openInCalcMode: 'Im Rechnermodus Öffnen',
        webhooksSection: 'Webhooks',
        sendAnswerWithoutEquation: 'Antwort Ohne Gleichung Senden',
        queueResultsForManualSending: 'Ergebnisse für Manuelles Senden Einreihen',
      },
      language: {
        title: 'Sprache',
        selectLanguage: 'Sprache Auswählen',
      },
      webhooks: {
        title: 'Webhooks',
        createNew: 'Neuen Webhook erstellen',
        enterTitle: 'Webhook-Titel eingeben (optional)',
        enterUrl: 'Webhook-URL eingeben (http:// oder https://)',
        add: 'Hinzufügen',
        myWebhooks: 'Meine Webhooks',
        noWebhooksYet: 'Noch keine Webhooks hinzugefügt',
        webhookTitle: 'Webhook-Titel (optional)',
        webhookUrl: 'Webhook-URL',
        invalidUrl: 'Ungültige URL',
        invalidUrlMessage: 'Webhook-URL muss gültig sein und mit http:// oder https:// beginnen',
        duplicateUrl: 'Doppelte URL',
        duplicateUrlMessage: 'Diese Webhook-URL existiert bereits.',
        success: 'Erfolg',
        webhookUpdated: 'Webhook erfolgreich aktualisiert!',
        saveError: 'Speicherfehler',
        couldNotSave: 'Webhook-URL konnte nicht gespeichert werden.',
      },
      bulkData: {
        title: 'Massendaten',
        items: 'Elemente',
        deleteAll: 'Alle Löschen',
        send: 'Senden',
        sending: 'Sende...',
        item: 'Element',
        activateWebhook: 'Aktivieren Sie mindestens einen Webhook um das Senden zu ermöglichen',
        noActiveUrls: 'Keine Aktiven URLs',
        activateMessage: 'Bitte aktivieren Sie mindestens eine Webhook-URL.',
        sendComplete: 'Senden Abgeschlossen',
        successfullySentTo: 'Erfolgreich gesendet an',
        endpoint: 'Endpunkt',
        endpoints: 'Endpunkte',
        failedToSendTo: 'Senden fehlgeschlagen an',
        sendError: 'Sendefehler',
        errorSending: 'Beim Senden der Daten ist ein Fehler aufgetreten.',
        saveErrorMessage: 'Beim Speichern der bearbeiteten Daten ist ein Fehler aufgetreten.',
        deleteError: 'Löschfehler',
        deleteErrorMessage: 'Beim Löschen des Elements ist ein Fehler aufgetreten.',
      },
      auth: {
        signInToContinue: 'Anmelden um fortzufahren',
        continueWithGoogle: 'Mit Google Fortfahren',
        signOut: 'Abmelden',
        anonymousCat: 'Anonyme Katze',
        guestUser: 'Gastbenutzer',
        firstUsersLifetime: 'Die Ersten 100 Benutzer Erhalten Lebenslangen Zugang',
        toPremium: 'zu Premium! - Hier anmelden',
        unlimitedCalculations: 'Unbegrenzte Berechnungen',
        webhookIntegration: 'Webhook-Integration',
        historySync: 'Verlauf & Synchronisation',
        comingSoon: '(bald)',
        authError: 'Authentifizierungsfehler',
        error: 'Fehler',
        failedToSignOut: 'Abmeldung fehlgeschlagen',
      },
      common: {
        duplicate: 'Duplikat',
        urlAlreadyAdded: 'Diese URL wurde bereits hinzugefügt.',
        privacyPolicy: 'Datenschutzrichtlinie',
        pro: 'PRO',
        beta: 'BETA',
      },
    },
  },
  pt: {
    settings: {
      title: 'Configurações',
      general: {
        title: 'Geral',
        inputBehavior: 'Comportamento de Entrada',
        muteVoiceOutput: 'Silenciar Saída de Voz (M)',
        newLineOnSend: 'Nova Linha ao Enviar',
        enableVibration: 'Ativar Vibração',
        openInCalcMode: 'Abrir no Modo Calculadora',
        webhooksSection: 'Webhooks',
        sendAnswerWithoutEquation: 'Enviar Resposta Sem Equação',
        queueResultsForManualSending: 'Enfileirar Resultados para Envio Manual',
      },
      language: {
        title: 'Idioma',
        selectLanguage: 'Selecionar Idioma',
      },
      webhooks: {
        title: 'Webhooks',
        createNew: 'Criar um novo webhook',
        enterTitle: 'Digite o título do webhook (opcional)',
        enterUrl: 'Digite a URL do webhook (http:// ou https://)',
        add: 'Adicionar',
        myWebhooks: 'Meus webhooks',
        noWebhooksYet: 'Nenhum webhook adicionado ainda',
        webhookTitle: 'Título do Webhook (opcional)',
        webhookUrl: 'URL do Webhook',
        invalidUrl: 'URL Inválida',
        invalidUrlMessage: 'A URL do webhook deve ser válida e começar com http:// ou https://',
        duplicateUrl: 'URL Duplicada',
        duplicateUrlMessage: 'Esta URL de webhook já existe.',
        success: 'Sucesso',
        webhookUpdated: 'Webhook atualizado com sucesso!',
        saveError: 'Erro ao Salvar',
        couldNotSave: 'Não foi possível salvar a URL do webhook.',
      },
      bulkData: {
        title: 'Dados em Massa',
        items: 'itens',
        deleteAll: 'Deletar Tudo',
        send: 'Enviar',
        sending: 'Enviando...',
        item: 'Item',
        activateWebhook: 'Ative pelo menos um webhook para habilitar o envio',
        noActiveUrls: 'Nenhuma URL Ativa',
        activateMessage: 'Por favor ative pelo menos uma URL de webhook.',
        sendComplete: 'Envio Completo',
        successfullySentTo: 'Enviado com sucesso para',
        endpoint: 'endpoint',
        endpoints: 'endpoints',
        failedToSendTo: 'Falha ao enviar para',
        sendError: 'Erro de Envio',
        errorSending: 'Ocorreu um erro ao enviar os dados.',
        saveErrorMessage: 'Ocorreu um erro ao salvar os dados editados.',
        deleteError: 'Erro de Exclusão',
        deleteErrorMessage: 'Ocorreu um erro ao deletar o item.',
      },
      auth: {
        signInToContinue: 'Faça login para continuar',
        continueWithGoogle: 'Continuar com Google',
        signOut: 'Sair',
        anonymousCat: 'Gato Anônimo',
        guestUser: 'Usuário Convidado',
        firstUsersLifetime: 'Os Primeiros 100 Usuários Ganham Acesso Vitalício',
        toPremium: 'ao Premium! - Cadastre-se aqui',
        unlimitedCalculations: 'Cálculos Ilimitados',
        webhookIntegration: 'Integração de Webhooks',
        historySync: 'Histórico e Sincronização',
        comingSoon: '(em breve)',
        authError: 'Erro de Autenticação',
        error: 'Erro',
        failedToSignOut: 'Falha ao sair',
      },
      common: {
        duplicate: 'Duplicado',
        urlAlreadyAdded: 'Esta URL já foi adicionada.',
        privacyPolicy: 'Política de Privacidade',
        pro: 'PRO',
        beta: 'BETA',
      },
    },
  },
  it: {
    settings: {
      title: 'Impostazioni',
      general: {
        title: 'Generale',
        inputBehavior: 'Comportamento Input',
        muteVoiceOutput: 'Silenzia Uscita Vocale (M)',
        newLineOnSend: 'Nuova Riga all\'Invio',
        enableVibration: 'Abilita Vibrazione',
        openInCalcMode: 'Apri in Modalità Calcolatrice',
        webhooksSection: 'Webhooks',
        sendAnswerWithoutEquation: 'Invia Risposta Senza Equazione',
        queueResultsForManualSending: 'Accoda Risultati per Invio Manuale',
      },
      language: {
        title: 'Lingua',
        selectLanguage: 'Seleziona Lingua',
      },
      webhooks: {
        title: 'Webhooks',
        createNew: 'Crea un nuovo webhook',
        enterTitle: 'Inserisci titolo webhook (opzionale)',
        enterUrl: 'Inserisci URL webhook (http:// o https://)',
        add: 'Aggiungi',
        myWebhooks: 'I miei webhooks',
        noWebhooksYet: 'Nessun webhook aggiunto ancora',
        webhookTitle: 'Titolo Webhook (opzionale)',
        webhookUrl: 'URL Webhook',
        invalidUrl: 'URL Non Valido',
        invalidUrlMessage: 'L\'URL del webhook deve essere valido e iniziare con http:// o https://',
        duplicateUrl: 'URL Duplicato',
        duplicateUrlMessage: 'Questo URL webhook esiste già.',
        success: 'Successo',
        webhookUpdated: 'Webhook aggiornato con successo!',
        saveError: 'Errore di Salvataggio',
        couldNotSave: 'Impossibile salvare l\'URL del webhook.',
      },
      bulkData: {
        title: 'Dati di Massa',
        items: 'elementi',
        deleteAll: 'Elimina Tutto',
        send: 'Invia',
        sending: 'Invio in corso...',
        item: 'Elemento',
        activateWebhook: 'Attiva almeno un webhook per abilitare l\'invio',
        noActiveUrls: 'Nessun URL Attivo',
        activateMessage: 'Per favore attiva almeno un URL webhook.',
        sendComplete: 'Invio Completato',
        successfullySentTo: 'Inviato con successo a',
        endpoint: 'endpoint',
        endpoints: 'endpoints',
        failedToSendTo: 'Invio fallito a',
        sendError: 'Errore di Invio',
        errorSending: 'Si è verificato un errore durante l\'invio dei dati.',
        saveErrorMessage: 'Si è verificato un errore durante il salvataggio dei dati modificati.',
        deleteError: 'Errore di Eliminazione',
        deleteErrorMessage: 'Si è verificato un errore durante l\'eliminazione dell\'elemento.',
      },
      auth: {
        signInToContinue: 'Accedi per continuare',
        continueWithGoogle: 'Continua con Google',
        signOut: 'Esci',
        anonymousCat: 'Gatto Anonimo',
        guestUser: 'Utente Ospite',
        firstUsersLifetime: 'I Primi 100 Utenti Ottengono Accesso a Vita',
        toPremium: 'a Premium! - Registrati qui',
        unlimitedCalculations: 'Calcoli Illimitati',
        webhookIntegration: 'Integrazione Webhooks',
        historySync: 'Cronologia e Sincronizzazione',
        comingSoon: '(prossimamente)',
        authError: 'Errore di Autenticazione',
        error: 'Errore',
        failedToSignOut: 'Impossibile disconnettersi',
      },
      common: {
        duplicate: 'Duplicato',
        urlAlreadyAdded: 'Questo URL è già stato aggiunto.',
        privacyPolicy: 'Informativa sulla Privacy',
        pro: 'PRO',
        beta: 'BETA',
      },
    },
  },
};